---
title: "Práctica 7"
subtitle: "Intervalos de confianza para la diferencia de parámetros"
format: 
  html: 
    toc: true
    toc-location: left
    toc-title: "Índice"
engine: knitr
filters:
  - webr
---

## 1. Introducción

Con esta práctica se utiliza R y RStudio para estimar (inferir) con un nivel de confianza determinado, el intervalo en el que se encuentra la diferencia de los parámetros (media y proporción) de dos poblaciones a partir de una muestra de cada una de las poblaciones.

Como en la práctica anterior, se puede calcular el intervalo en el que se puede asegurar que se encuentra la diferencia con un determinado nivel de confianza, obteniendo lo que se conoce como Intervalo de Confianza, con un límite inferior $L_{i}$ y un límite superior $L_{s}$:

$$\text{Intervalo de confianza con nivel de confianza } 1-\alpha=(L_{i}, L_{s})$$ En la expresión del nivel de confianza aparece un valor $\alpha$ (alfa) que se denomina nivel de error o nivel de significación, y representa lo contrario que el nivel de confianza.

Cuando el intervalo de confianza:

- Sí contiene el valor 0, se puede afirmar que la diferencia de los parámetros de ambas poblaciones NO es significativa.
- No contiene el valor 0, se puede afirmar que la diferencia entre los parámetros de ambas poblaciones SÍ es significativa y además:
  - Si los extremos del intervalo son negativos, se puede afirmar que el parámetro de la primera población es menor que el de la segunda.
  - Si los extremos del intervalo son positivos, se puede afirmar que el parámetro de la primera población es mayor que el de la segunda.

En la siguiente tabla se indican las fórmulas para calcular las diferencias de los parámetros poblacionales y su posible programación utilizando el lenguaje R. En el caso de la media se distingue entre muestras independientes y muestras relacionadas o pareadas. En este último caso realmente se comparan dos variables diferentes, y se manejan parejas de valores, normalmente un valor de la variable en una situación (por ejemplo, el peso de una persona) y otro valor de la misma variable en otra situación (por ejemplo, el peso de la misma persona al finalizar una dieta).

En la tabla sólo se muestran las situaciones sobre las que se probarán ejemplos en esta práctica, por ejemplo, no aparecen las fórmulas para la diferencia de medias con varianzas poblacionales conocidas, o con varianzas poblacionales desconocidas pero iguales. En la tabla se considera el caso general de varianzas poblacionales desconocidas y diferentes.

+-------------------------------------------------------------+------------------------------+----------------------------------------------------------------------------------------------------------+---------------------------------------------------------------+
| Diferencia a calcular                                       | Varianzas conocidas          | Intervalo de confianza (Li, Ls)                                                                          | Código R                                                      |
+=============================================================+==============================+==========================================================================================================+===============================================================+
| Diferencia de medias de dos poblaciones $(\mu_{1}-\mu_{2})$ | Sí                           | $$L_{i} = \bar{x}-\bar{y}-z_{\frac{\alpha}{2}}\sqrt{\frac{\sigma^{2}_{X}}{n}+\frac{\sigma^{2}_{Y}}{m}}$$ | ``` r                                                         |
|                                                             |                              |                                                                                                          | x=muestra de X                                                |
|                                                             |                              | $$L_{s} = \bar{x}-\bar{y}+z_{\frac{\alpha}{2}}\sqrt{\frac{\sigma^{2}_{X}}{n}+\frac{\sigma^{2}_{Y}}{m}}$$ | y=muestra de Y                                                |
|                                                             |                              |                                                                                                          | n=length(x)                                                   |
|                                                             |                              |                                                                                                          | m=length(y)                                                   |
|                                                             |                              |                                                                                                          | mx=mean(x)                                                    |
|                                                             |                              |                                                                                                          | my=mean(y)                                                    |
|                                                             |                              |                                                                                                          | dx^2=varianza poblacional de X                                |
|                                                             |                              |                                                                                                          | dy^2=varianza poblacional de Y                                |
|                                                             |                              |                                                                                                          | z=qnorm(1-alfa/2,0,1)                                         |
|                                                             |                              |                                                                                                          | Li=mx-my-z*sqrt((dx^2/n)+(dy^2/m))                            |
|                                                             |                              |                                                                                                          | Ls=mx-my+z*sqrt((dx^2/n)+(dy^2/m))                            |
|                                                             |                              |                                                                                                          | ```                                                           |
+-------------------------------------------------------------+------------------------------+----------------------------------------------------------------------------------------------------------+---------------------------------------------------------------+
|                                                             | No                           | $$L_{i} = \bar{x}-\bar{y}-z_{\frac{\alpha}{2}}\sqrt{\frac{s^{2}_{X}}{n}+\frac{s^{2}_{Y}}{m}}$$           | ``` r                                                         |
|                                                             |                              |                                                                                                          | x=muestra de X                                                |
|                                                             | $$n, m \ge 30$$              | $$L_{s} = \bar{x}-\bar{y}+z_{\frac{\alpha}{2}}\sqrt{\frac{s^{2}_{X}}{n}+\frac{s^{2}_{Y}}{m}}$$           | y=muestra de Y                                                |
|                                                             |                              |                                                                                                          | n=length(x)                                                   |
|                                                             |                              |                                                                                                          | m=length(y)                                                   |
|                                                             |                              |                                                                                                          | mx=mean(x)                                                    |
|                                                             |                              |                                                                                                          | my=mean(y)                                                    |
|                                                             |                              |                                                                                                          | sx=sd(x)                                                      |
|                                                             |                              |                                                                                                          | sy=sd(y)                                                      |
|                                                             |                              |                                                                                                          | z=qnorm(1-alfa/2,0,1)                                         |
|                                                             |                              |                                                                                                          | Li=mx-my-z*sqrt((sx^2/n)+(sy^2/m))                            |
|                                                             |                              |                                                                                                          | Ls=mx-my+z*sqrt((sx^2/n)+(sy^2/m))                            |
|                                                             |                              |                                                                                                          | ```                                                           |
+-------------------------------------------------------------+------------------------------+----------------------------------------------------------------------------------------------------------+---------------------------------------------------------------+
|                                                             | No                           | $$L_{i} = \bar{x}-\bar{y}-(t_{\frac{\alpha}{2},n+m-2})(s_{p})\sqrt{\frac{1}{n}+\frac{1}{m}}$$            | ``` r                                                         |
|                                                             |                              |                                                                                                          | x=muestra de X                                                |
|                                                             | $$n,m<30$$                   | $$L_{s} = \bar{x}-\bar{y}+(t_{\frac{\alpha}{2},n+m-2})(s_{p})\sqrt{\frac{1}{n}+\frac{1}{m}}$$            | y=muestra de Y                                                |
|                                                             |                              |                                                                                                          | n=length(x)                                                   |
|                                                             | $$\sigma_{X} = \sigma_{Y}$$  | $$s_{p} =\sqrt{\frac{(n-1)s^2_{X}+(m-1)s^2_{Y}}{n+m-2}}$$                                                | m=length(y)                                                   |
|                                                             |                              |                                                                                                          | mx=mean(x)                                                    |
|                                                             |                              |                                                                                                          | my=mean(y)                                                    |
|                                                             |                              |                                                                                                          | sx=sd(x)                                                      |
|                                                             |                              |                                                                                                          | sy=sd(y)                                                      |
|                                                             |                              |                                                                                                          | sp=sqrt(((n-1)*sx^2+(m-1)*sy^2)/(n+m-2))                      |
|                                                             |                              |                                                                                                          | t=qt(1-alfa/2,n+m-2)                                          |
|                                                             |                              |                                                                                                          | Li=m1-m2-t*sp*sqrt((1/n)+(1/m))                               |
|                                                             |                              |                                                                                                          | Ls=m1-m2+t*sp*sqrt((1/n)+(1/m))                               |
|                                                             |                              |                                                                                                          | ```                                                           |
+-------------------------------------------------------------+------------------------------+----------------------------------------------------------------------------------------------------------+---------------------------------------------------------------+
|                                                             | No                           | $$L_{i} = \bar{x}-\bar{y}-t_{\frac{\alpha}{2},v}\sqrt{\frac{s^{2}_{X}}{n}+\frac{s^{2}_{Y}}{m}}$$         | ``` r                                                         |
|                                                             |                              |                                                                                                          | x=muestra de X                                                |
|                                                             | $$n,m<30$$                   | $$L_{s} = \bar{x}-\bar{y}+t_{\frac{\alpha}{2},v}\sqrt{\frac{s^{2}_{X}}{n}+\frac{s^{2}_{Y}}{m}}$$         | y=muestra de Y                                                |
|                                                             |                              |                                                                                                          | n=length(x)                                                   |
|                                                             | $$\sigma_{X}\ne \sigma_{Y}$$ | $$v=\frac{(\frac{s^2_{X}}{n}+\frac{s^2_{Y}}{m})^2}{\frac{s^4_{X}}{n^2(n-1)}+\frac{s^4_{Y}}{m^2(m-1)}}$$  | m=length(y)                                                   |
|                                                             |                              |                                                                                                          | mx=mean(x)                                                    |
|                                                             |                              |                                                                                                          | my=mean(y)                                                    |
|                                                             |                              |                                                                                                          | sx=sd(x)                                                      |
|                                                             |                              |                                                                                                          | sy=sd(y)                                                      |
|                                                             |                              |                                                                                                          | v=((sx^2/n+sy^2/m)^2)/((sx^4/(n^2*(n-1)))+(sy^4/(m^2*(m-1)))) |
|                                                             |                              |                                                                                                          | t=qt(1-alfa/2, v)                                             |
|                                                             |                              |                                                                                                          | Li=mx-my-t*sqrt((sx^2/n)+(sy^2/m))                            |
|                                                             |                              |                                                                                                          | Ls=mx-my+t*sqrt((sx^2/n)+(sy^2/m))                            |
|                                                             |                              |                                                                                                          | ```                                                           |
+-------------------------------------------------------------+------------------------------+----------------------------------------------------------------------------------------------------------+---------------------------------------------------------------+
|                                                             | Muestras pareadas            | $$L_{i} = \bar{d}-z_{\frac{\alpha}{2}}\frac{s_{D}}{\sqrt{n}}$$                                           | ``` r                                                         |
|                                                             |                              |                                                                                                          | d=muestra de X – muestra de Y                                 |
|                                                             | $$n \ge 30$$                 | $$L_{s} = \bar{d}+z_{\frac{\alpha}{2}}\frac{s_{D}}{\sqrt{n}}$$                                           | n=length(d)                                                   |
|                                                             |                              |                                                                                                          | m=mean(d)                                                     |
|                                                             |                              | $$D = X-Y$$                                                                                              | s=sd(d)                                                       |
|                                                             |                              |                                                                                                          | z=qnorm(1-alfa/2,0,1)                                         |
|                                                             |                              |                                                                                                          | Li=m-z*(s/sqrt(n))                                            |
|                                                             |                              |                                                                                                          | Ls=m+z*(s/sqrt(n))                                            |
|                                                             |                              |                                                                                                          | ```                                                           |
+-------------------------------------------------------------+------------------------------+----------------------------------------------------------------------------------------------------------+---------------------------------------------------------------+
|                                                             | Muestras pareadas            | $$L_{i} = \bar{d}-t_{\frac{\alpha}{2},n-1}\frac{s_{D}}{\sqrt{n}}$$                                       | ``` r                                                         |
|                                                             |                              |                                                                                                          | d= muestra de X – muestra de Y                                |
|                                                             | $$n < 30$$                   | $$L_{s} = \bar{d}+t_{\frac{\alpha}{2},n-1}\frac{s_{D}}{\sqrt{n}}$$                                       | n=length(d)                                                   |
|                                                             |                              |                                                                                                          | m=mean(d)                                                     |
|                                                             |                              | $$D = X-Y$$                                                                                              | s=sd(d)                                                       |
|                                                             |                              |                                                                                                          | t=qt(1-alfa/2,n-1)                                            |
|                                                             |                              |                                                                                                          | Li=m-t*(s/sqrt(n))                                            |
|                                                             |                              |                                                                                                          | Ls=m+t*(s/sqrt(n))                                            |
|                                                             |                              |                                                                                                          | ```                                                           |
+-------------------------------------------------------------+------------------------------+----------------------------------------------------------------------------------------------------------+---------------------------------------------------------------+

+-----------------------------------------------+-----------------+--------------------------------------------------------------------------------------------------------------------------------------------------+------------------------------------------------+
| Diferencia a calcular                         | Muestras        | Intervalo de confianza $(L_{i}, L_{s})$                                                                                                          | Código R                                       |
+===============================================+=================+==================================================================================================================================================+================================================+
| Diferencia de proporciones de dos poblaciones | $$n, m \ge 30$$ | $$L_{i} = \hat{p}_{1}-\hat{p}_{2}-z_{\frac{\alpha}{2}}\sqrt{\frac{\hat{p}_{1}(1-\hat{p}_{1})}{n_{1}}+\frac{\hat{p}_{2}(1-\hat{p}_{2})}{n_{2}}}$$ | ``` r                                          |
|                                               |                 |                                                                                                                                                  | n1,n2=tamaño de muestras                       |
| $$(p_{1}-p_{2})$$                             |                 | $$L_{s} = \hat{p}_{1}-\hat{p}_{2}+z_{\frac{\alpha}{2}}\sqrt{\frac{\hat{p}_{1}(1-\hat{p}_{1})}{n_{1}}+\frac{\hat{p}_{2}(1-\hat{p}_{2})}{n_{2}}}$$ | p1,p2=proporciones en muestras                 |
|                                               |                 |                                                                                                                                                  | z=qnorm(1-alfa/2,0,1)                          |
|                                               |                 |                                                                                                                                                  | Li=p1-p2-z*sqrt((p1*(1-p1)/n1)+(p2*(1-p2)/n2)) |
|                                               |                 |                                                                                                                                                  | Ls=p1-p2+z*sqrt((p1*(1-p1)/n1)+(p2*(1-p2)/n2)) |
|                                               |                 |                                                                                                                                                  | ```                                            |
+-----------------------------------------------+-----------------+--------------------------------------------------------------------------------------------------------------------------------------------------+------------------------------------------------+

Existen en R funciones predefinidas que se pueden utilizar para los cálculos de algunos intervalos sin tener que programar las fórmulas de la tabla anterior.

Son las funciones predefinidas *t.test()* y *prop.test()*, y la función *z.test()* del paquete *BSDA*.

+-------------------------------------------------------------+------------------------------+------------------------------------------+----------------------------------+
| Diferencia a calcular                                       | Varianzas conocidas          | Código R                                 | Ejemplo                          |
+=============================================================+==============================+==========================================+==================================+
| Diferencia de medias de dos poblaciones $(\mu_{1}-\mu_{2})$ | Sí                           | ``` r                                    | ``` r                            |
|                                                             |                              | test= z.test(muestra de X,               | x=muestra de X                   |
|                                                             |                              |              muestra de Y,               | y=muestra de Y                   |
|                                                             |                              |              sigma.x=desviación          | dx=1.5                           |
|                                                             |                              |              poblacional                 | dy=2.3                           |
|                                                             |                              |              de X,                       | alfa=0.05                        |
|                                                             |                              |              sigma.y=desviación          | test=z.test(x,                   |
|                                                             |                              |              poblacional                 |             y,                   |
|                                                             |                              |              de Y,                       |             sigma.x = dx,        |
|                                                             |                              |              conf.level=1-alfa)          |             sigma.y = dy,        |
|                                                             |                              | ```                                      |             conf.level = 1-alfa) |
|                                                             |                              |                                          | test$conf.int                    |
|                                                             |                              | Intervalo:                               | ```                              |
|                                                             |                              |                                          |                                  |
|                                                             |                              | ``` r                                    |                                  |
|                                                             |                              | test$conf.int                            |                                  |
|                                                             |                              | ```                                      |                                  |
+-------------------------------------------------------------+------------------------------+------------------------------------------+----------------------------------+
|                                                             | No                           | ``` r                                    | ``` r                            |
|                                                             |                              | test= z.test(muestra de X,               | x=rnorm(40,5,1)                  |
|                                                             | $$n, m \ge 30$$              |              muestra de Y,               | y=rnorm(50,6,1)                  |
|                                                             |                              |              sigma.x=desviación          | alfa=0.05                        |
|                                                             |                              |              muestral de X,              | test=z.test(x,                   |
|                                                             |                              |              sigma.y=desviación          |             y,                   |
|                                                             |                              |              muestral de Y,              |             sigma.x = sd(x),     |
|                                                             |                              |              conf.level=1-alfa)          |             sigma.y = sd(y),     |
|                                                             |                              | ```                                      |             conf.level = 1-alfa) |
|                                                             |                              |                                          | test$conf.int                    |
|                                                             |                              | Intervalo:                               | ```                              |
|                                                             |                              |                                          |                                  |
|                                                             |                              | ``` r                                    |                                  |
|                                                             |                              | test$conf.int                            |                                  |
|                                                             |                              | ```                                      |                                  |
+-------------------------------------------------------------+------------------------------+------------------------------------------+----------------------------------+
|                                                             | No                           | ``` r                                    | ``` r                            |
|                                                             |                              | test= t.test(muestra de X,               | x=c(4.5, 5.2, 5.3, 4.7, 5, 6.3)  |
|                                                             | $$n,m<30$$                   |              muestra de Y,               | y=c(6.7, 5.1, 6.1, 4.3)          |
|                                                             |                              |              conf.level=1-alfa,          | alfa=0.05                        |
|                                                             | $$\sigma_{X} = \sigma_{Y}$$  |              var.equal=TRUE)             | test=t.test(x,                   |
|                                                             |                              | ```                                      |             y,                   |
|                                                             |                              |                                          |             conf.level = 1-alfa, |
|                                                             |                              | Intervalo:                               |             var.equal=TRUE)      |
|                                                             |                              |                                          | test$conf.int                    |
|                                                             |                              | ``` r                                    | ```                              |
|                                                             |                              | test$conf.int                            |                                  |
|                                                             |                              | ```                                      |                                  |
+-------------------------------------------------------------+------------------------------+------------------------------------------+----------------------------------+
|                                                             | No                           | ``` r                                    | ``` r                            |
|                                                             |                              | test= t.test(muestra de X,               | x=c(4.5, 5.2, 5.3, 4.7, 5, 6.3)  |
|                                                             | $$n,m<30$$                   |              muestra de Y,               | y=c(6.7, 5.1, 6.1, 4.3)          |
|                                                             |                              |              conf.level=1-alfa,          | alfa=0.05                        |
|                                                             | $$\sigma_{X}\ne \sigma_{Y}$$ |              var.equal=FALSE)            | test=t.test(x,                   |
|                                                             |                              | ```                                      |             y,                   |
|                                                             |                              |                                          |             conf.level = 1-alfa, |
|                                                             |                              | Intervalo:                               |             var.equal=FALSE)     |
|                                                             |                              |                                          | test$conf.int                    |
|                                                             |                              | ``` r                                    | ```                              |
|                                                             |                              | test$conf.int                            |                                  |
|                                                             |                              | ```                                      |                                  |
+-------------------------------------------------------------+------------------------------+------------------------------------------+----------------------------------+
|                                                             | Muestras pareadas            | ``` r                                    | ``` r                            |
|                                                             |                              | test= z.test(diferencia                  | x=rnorm(40,5,1)                  |
|                                                             | $$n \ge 30$$                 |              entre las                   | y=rnorm(40,6,1)                  |
|                                                             |                              |              muestras,                   | alfa=0.05                        |
|                                                             |                              |              sigma.x=desviación muestral | d=x-y                            |
|                                                             |                              |              de la diferencia            | test=z.test(d,                   |
|                                                             |                              |              entre las muestras,         |             sigma.x = sd(d),     |
|                                                             |                              |              conf.level=1-alfa)          |             conf.level = 1-alfa) |
|                                                             |                              | ```                                      | test$conf.int                    |
|                                                             |                              |                                          | ```                              |
|                                                             |                              | Intervalo:                               |                                  |
|                                                             |                              |                                          |                                  |
|                                                             |                              | ``` r                                    |                                  |
|                                                             |                              | test$conf.int                            |                                  |
|                                                             |                              | ```                                      |                                  |
+-------------------------------------------------------------+------------------------------+------------------------------------------+----------------------------------+
|                                                             | Muestras pareadas            | ``` r                                    | ``` r                            |
|                                                             |                              | test= t.test(muestra de X,               | x=c(4.5, 5.2, 5.3, 4.7)          |
|                                                             | $$n < 30$$                   |              muestra de Y,               | y=c(6.7, 5.1, 6.1, 4.3)          |
|                                                             |                              |              conf.level=1-alfa,          | alfa=0.05                        |
|                                                             |                              |              paired=TRUE)                | test=t.test(x,                   |
|                                                             |                              | ```                                      |             y,                   |
|                                                             |                              |                                          |             conf.level = 1-alfa, |
|                                                             |                              | Intervalo:                               |             paired=TRUE)         |
|                                                             |                              |                                          | test$conf.int                    |
|                                                             |                              | ``` r                                    | ```                              |
|                                                             |                              | test$conf.int                            |                                  |
|                                                             |                              | ```                                      |                                  |
+-------------------------------------------------------------+------------------------------+------------------------------------------+----------------------------------+

+-----------------------------------------------+-----------------+-----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+-------------------------------------+
| Diferencia a calcular                         | Muestras        | Código R                                                                                                                                                                                | Ejemplo                             |
+===============================================+=================+=========================================================================================================================================================================================+=====================================+
| Diferencia de proporciones de dos poblaciones | $$n, m \ge 30$$ | ``` r                                                                                                                                                                                   | ``` r                               |
|                                               |                 | test= prop.test(c(ng1,ng2),                                                                                                                                                             | n1=100                              |
| $$(p_{1}-p_{2})$$                             |                 |                 c(n1,n2),                                                                                                                                                               | n2=100                              |
|                                               |                 |                 conf.level=1-alfa,                                                                                                                                                      | ng1=20                              |
|                                               |                 |                 correct=FALSE)                                                                                                                                                          | ng2=70                              |
|                                               |                 | ```                                                                                                                                                                                     | alfa=0.05                           |
|                                               |                 |                                                                                                                                                                                         | test=prop.test(c(ng1,ng2),          |
|                                               |                 | Intervalo:                                                                                                                                                                              |                c(n1,n2),            |
|                                               |                 |                                                                                                                                                                                         |                conf.level = 1-alfa, |
|                                               |                 | ``` r                                                                                                                                                                                   |                correct=FALSE)       |
|                                               |                 | test$conf.int                                                                                                                                                                           | test$conf.int                       |
|                                               |                 | ```                                                                                                                                                                                     | ```                                 |
|                                               |                 |                                                                                                                                                                                         |                                     |
|                                               |                 | NOTA: *n1* y *n2* son los tamaños de las muestras.                                                                                                                                      |                                     |
|                                               |                 |                                                                                                                                                                                         |                                     |
|                                               |                 | *ng1* y *ng2* son los tamaños de los grupos de datos de las muestras para los que se calculan las proporciones, es decir, las proporciones muestrales serían *p1=ng1/n1* y *p2=ng2/n2*. |                                     |
+-----------------------------------------------+-----------------+-----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+-------------------------------------+

::: {.callout-tip collapse="true"}
## Copia los ejemplos de uso de la tabla y prúebalos tú mismo aquí

```{webr-r}

```
:::

## 2. Ejemplo: Intervalo de confianza para la diferencia de medias de calificaciones de estudiantes del turno de mañana y del turno de tarde (muestras grandes e independientes)

***ENUNCIADO***

**Mediante una encuesta, se saben las calificaciones de acceso a la universidad de 42 estudiantes del turno de mañana y de 32 estudiantes del turno de tarde de un curso de la asignatura Estadística del Grado en Ingeniería en Sistemas de Información de la Universidad de Alcalá, de una población de 52 matriculados en el turno de mañana y 56 en el turno de tarde. Si se supone que las calificaciones tienen una distribución Normal, responder a la siguiente pregunta:**

a)  **Dibujar un diagrama con los intervalos de confianza de las dos poblaciones por separado, con un nivel de confianza del 95%, para hacer una comparación visual.**
b)  **Calcular el intervalo de confianza para la diferencia de medias poblacionales de las calificaciones de los turnos de mañana y tarde con nivel de confianza del 95%.**
c)  **Dibujar la función de densidad de probabilidad del estimador (sin estandarizar) de la diferencia de medias poblacionales.**
d)  **Calcular el intervalo de confianza con la función *z.test* del paquete *BSDA*.**
e)  **¿Existe una diferencia significativa entre las medias de las dos poblaciones (mañana y tarde)?**

***SOLUCIÓN***

Primero leemos el archivo encuesta.csv y guardamos en dos vectores las muestras de notas de turno de mañana (grupos A1 y A2) y del turno de tarde (grupos B1 y B2):

```{webr-r}
encuesta=read.csv2("https://raw.githubusercontent.com/nataliamontoyagom/interactiveStatisticsWebsite/main/encuesta.csv")
encuesta.mañana=encuesta[(encuesta$GRUPO=="A1")|(encuesta$GRUPO=="A2"),]
encuesta.tarde=encuesta[(encuesta$GRUPO=="B1")|(encuesta$GRUPO=="B2"),]
notaM=encuesta.mañana$NOTA
notaT=encuesta.tarde$NOTA
```

a)  **Dibujar un diagrama con los intervalos de confianza de las dos poblaciones por separado, con un nivel de confianza del 95%, para hacer una comparación visual.**

El intervalo de confianza de los alumnos de mañana es:

```{webr-r}
nM=length(notaM)
mM=mean(notaM)
sM=sd(notaM)
alfa=1-0.95
z=qnorm(1-alfa/2,0,1)
(LiM=mM-z*(sM/sqrt(nM)))
(LsM=mM+z*(sM/sqrt(nM)))
```

El intervalo de confianza de los alumnos de tarde es:

```{webr-r}
nT=length(notaT)
mT=mean(notaT)
sT=sd(notaT)
alfa=1-0.95
z=qnorm(1-alfa/2,0,1)
(LiT=mT-z*(sT/sqrt(nT)))
(LsT=mT+z*(sT/sqrt(nT)))
```

Podemos dibujarlos con *plot* y *lines*:

```{webr-r}
plot(c(0.95,0.95,0.95,0.95),c(LiM, LsM, LiT, LsT), xlim = c(0.9,1))
lines(c(0.95,0.95),c(LiM,LsM))
lines(c(0.95,0.95),c(LiT,LsT),col="red")
```

Vemos que los dos intervalos no se solapan, lo cual es un indicio de que no va a haber coincidencia de medias, aunque lo tendremos que demostrar calculando el intervalo de la diferencia de medias.

También de puede hacer el dibujo, utilizando la función *ggplot()* del paquete *ggplot2*.

```{webr-r}
install.packages("ggplot2")
library(ggplot2)
install.packages("Rmisc")
library(Rmisc)
notas.turnos = data.frame (NOTA = c(notaM,notaT),
                           TURNO = c(rep("Mañana",nM),rep("Tarde",nT)))
(resumen=summarySE(notas.turnos, measurevar="NOTA", groupvars="TURNO"))
g.puntos=ggplot(resumen, aes(x=TURNO, y=NOTA)) + geom_point(size=3)+ylim(7,9)
g.puntos
g.intervalos = g.puntos + geom_errorbar(aes(ymin=NOTA-ci, ymax=NOTA+ci),
width = 0.2) + ggtitle("Intervalos al 95% para la media de las nota según grupo")
g.intervalos
```

b)  **Calcular el intervalo de confianza para la diferencia de medias poblacionales de las calificaciones de los turnos de mañana y tarde con nivel de confianza del 95%.**

```{webr-r}
alfa = 1-0.95
z=qnorm(1-alfa/2,0,1)
(Li=mM-mT-z*sqrt((sM^2/nM)+(sT^2/nT)))
(Ls=mM-mT+ z*sqrt((sM^2/nM)+(sT^2/nT)))
```

El intervalo de confianza para la diferencia de medias entre los grupos de mañana y tarde es \[0.2597101, 1.249159\].

c)  **Dibujar la función de densidad de probabilidad del estimador (sin estandarizar) de la diferencia de medias poblacionales.**

El estimador sin estandarizar es una variable aleatoria con distribución Normal:
$$Normal(\bar{x}-\bar{y},\sqrt{\frac{s^2_{X}}{n}+\frac{s^2_{Y}}{m}})$$

Por tanto, la función de densidad de probabilidad se puede dibujar de la siguiente forma:

```{webr-r}
m <- mM - mT
curve(dnorm(x,mM-mT,sqrt((sM^2/nM)+(sT^2/nT))),-1,2)
segments(-1,0,2,0)
segments(Li,0, Li,dnorm(Li,m,sqrt((sM^2/nM)+(sT^2/nT))))
segments(Ls,0, Ls,dnorm(Li,m,sqrt((sM^2/nM)+(sT^2/nT))))
text(Li,0,paste("Li=",as.character(round(Li,2))),cex=0.8)
text(Ls,0,paste("Ls=",as.character(round(Ls,2))),cex=0.8)
```

d)  **Calcular el intervalo de confianza con la función z.test del paquete BSDA.**

```{webr-r}
install.packages("BSDA")
library(BSDA)
z.test(notaM,notaT,sigma.x=sM,sigma.y=sT,conf.level=0.95)
```

Podemos comprobar que se obtiene el mismo intervalo que aplicando las fórmulas.

e)  **¿Existe una diferencia significativa entre las medias de las dos poblaciones (mañana y tarde)?**

Como el 0 no está incluido en el intervalo \[0.2597101, 1.2491589\], se puede afirmar con un nivel de confianza del 95% que **SÍ hay diferencia significativa entre la media de las calificaciones de los estudiantes de los turnos de mañana y tarde, y que la media de las calificaciones de los estudiantes del turno de mañana es mayor que la media de las calificaciones de los estudiantes del turno de tarde**, porque los extremos de los intervalos son positivos.

## 3. Ejemplo: Intervalo de confianza para la diferencia de medias del tiempo que duermen los estudiantes en días laborables y en días festivos (muestras grandes y pareadas)

***ENUNCIADO***

**Mediante la encuesta del ejemplo anterior se sabe el tiempo que duermen los días laborables 74 estudiantes de una población de 108 matriculados. Se ha averiguado que los días festivos los estudiantes duermen un 10% más de tiempo que en días laborables. Si se supone que el tiempo que duermen tanto en días laborables como en festivos tiene una distribución Normal, responder a la siguiente pregunta:**

a)  **Calcular el intervalo de confianza para la diferencia de medias poblacionales del tiempo que duermen los estudiantes en días laborables y festivos, con nivel de confianza del 95%.**
b)  **Calcular el intervalo de confianza con la función *z.test* del paquete *BSDA*.**
c)  **¿Existe una diferencia significativa entre las medias de las dos poblaciones?**

***SOLUCIÓN***

a)  **Calcular el intervalo de confianza para la diferencia de medias poblacionales del tiempo que duermen los estudiantes en días laborables y festivos, con nivel de confianza del 95%.**

Primero guardamos en dos vectores las muestras de las horas que duermen los estudiantes en días laborables y en festivos:

```{webr-r}
dormirL=encuesta$DORMIR
dormirF=1.1*encuesta$DORMIR #Un 10% más que los laborables
alfa=1-0.95
d=dormirL-dormirF
m=mean(d)
s=sd(d)
n=length(d)
z=qnorm(1-alfa/2,0,1)
(Li=m-z*(s/sqrt(n)))
(Ls=m+z*(s/sqrt(n)))
```

El intervalo de confianza de la diferencia de media de las horas que duermen en laborables y festivos es \[-0.6978706, -0.6561835\].

b)  **Calcular el intervalo de confianza con la función *z.test* del paquete *BSDA*.**

```{webr-r}
z.test(d, sigma.x=s ,conf.level=0.95)
```

Podemos comprobar que se obtiene el mismo intervalo que aplicando las fórmulas.

c)  **¿Existe una diferencia significativa entre las medias de las dos poblaciones?**

Como el 0 no está incluido en el intervalo, se puede afirmar con un nivel de confianza del 95% que **SÍ hay diferencia significativa entre la media del tiempo que duermen los estudiantes los días laborables y los días festivos, y que la media del tiempo que duermen los días laborables es menor que la media del tiempo que duermen los días festivos**, porque los extremos de los intervalos son negativos.

## 4. Ejemplo: Intervalo de confianza para la diferencia de proporciones de estudiantes que tienen móvil Android en el turno de mañana y en el turno de tarde (muestras grandes e independientes)

***ENUNCIADO***

**Mediante una encuesta se sabe que en una muestra de 42 estudiantes del turno de mañana de la asignatura Estadística, 27 tienen teléfonos móviles con sistema operativo Android, y que en una muestra de 32 estudiantes del turno de tarde, 23 tienen también teléfono Android. La población es de 52 matriculados por la mañana y 56 por la tarde. Responder a las siguientes preguntas:**

a)  **Calcular el intervalo de confianza para la diferencia de las proporciones poblacionales de estudiantes que tienen móvil Android en los turnos de mañana y tarde, con un nivel de confianza del 95%.**
b)  **Calcular el intervalo de confianza con la función *prop.test*.**
c)  **¿Existe una diferencia significativa entre las proporciones de las dos poblaciones?**

***SOLUCIÓN***

a)  **Calcular el intervalo de confianza para la diferencia de las proporciones poblacionales de estudiantes que tienen móvil Android en los turnos de mañana y tarde, con un nivel de confianza del 95%.**

Primero calculamos el tamaño de las muestras y de los estudiantes que usan Android en cada muestra.

```{webr-r}
soM=encuesta.mañana$SO
soT=encuesta.tarde$SO

nM=length(soM)
nT=length(soT)

nMA=length(soM[soM=="Android"])
nTA=length(soT[soT=="Android"])
```

Y se aplican las fórmulas:

```{webr-r}
alfa=1-0.95
pM=nMA/nM
pT=nTA/nT
z=qnorm(1-alfa/2,0,1)
(Li=pM-pT-z*sqrt((pM*(1-pM)/nM)+(pT*(1-pT)/nT)))
(Ls=pM-pT+z*sqrt((pM*(1-pM)/nM)+(pT*(1-pT)/nT)))
```

El intervalo de confianza de la diferencia de proporciones de estudiantes que tienen móvil Android en los turnos de mañana y tarde es \[-0.2886515, 0.1368658\].

b)  **Calcular el intervalo de confianza con la función *prop.test*.**

```{webr-r}
prop.test(c(nMA,nTA), c(nM,nT), conf.level = 1-alfa, correct=FALSE)
```

Podemos comprobar que se obtiene el mismo intervalo que aplicando las fórmulas.

c)  **¿Existe una diferencia significativa entre las proporciones de las dos poblaciones?**

Como el 0 está incluido en el intervalo \[-0.2886515, 0.1368658\], se puede afirmar con un nivel de confianza del 95% que **NO hay diferencia significativa entre las proporciones de móvil Android de los estudiantes de los turnos de mañana y tarde**.

## 5. Ejercicios propuestos

1.  Mediante una encuesta, se sabe el tiempo en minutos del viaje a la Escuela Politécnica de 42 estudiantes del turno de mañana y de 32 estudiantes del turno de tarde de un curso de la asignatura Estadística del Grado en Ingeniería en Sistemas de Información de la Universidad de Alcalá, de una población de 52 matriculados en el turno de mañana y 56 en el turno de tarde. Si se supone que las calificaciones tienen una distribución Normal, responder a la siguiente pregunta:
    a.  Calcular el intervalo de confianza para la diferencia de medias poblacionales del tiempo del viaje a la Escuela de los turnos de mañana y tarde con nivel de confianza del 95%. ¿Existe una diferencia significativa entre las medias de las dos poblaciones?
2.  Mediante la encuesta se sabe el tiempo en minutos del viaje de ida a la Escuela Politécnica de 74 estudiantes de una población de 108 matriculados. Se ha averiguado que el viaje de regreso dura un 10% menos que el de ida. Si se supone que el tiempo del viaje, tanto de ida como de vuelta, tiene una distribución Normal, responder a la siguiente pregunta:
    a.  Calcular el intervalo de confianza para la diferencia de medias poblacionales del tiempo de viaje de ida y del tiempo de viaje de vuelta de los estudiantes, con nivel de confianza del 95%. ¿Existe una diferencia significativa entre las medias de las dos poblaciones?
3.  Mediante la encuesta se sabe que en una muestra de 42 estudiantes del turno de mañana, 13 tienen una línea telefónica contratada con las compañías Jazzte/Orange/Simyo, y que en una muestra de 32 estudiantes del turno de tarde, 13 tienen también una línea telefónica contratada con las compañías Jazzte/Orange/Simyo. La población es de 52 matriculados por la mañana y 56 por la tarde. Responder a las siguientes preguntas:
    a.  Calcular el intervalo de confianza para la diferencia de las proporciones poblacionales de estudiantes que tienen una línea telefónica contratada con las compañías Jazzte/Orange/Simyo en los turnos de mañana y tarde, con un nivel de confianza del 95%. ¿Existe una diferencia significativa entre las proporciones de las dos poblaciones?
