---
title: "Práctica 6"
subtitle: "Intervalos de confianza para parámetros"
format: 
  html: 
    toc: true
    toc-location: left
    toc-title: "Índice"
engine: knitr
filters:
  - webr
---

## 1. Introducción

Con esta práctica se utiliza R y RStudio para estimar (inferir) con un nivel de confianza determinado, el intervalo en el que se encuentra el valor de los parámetros de una población (media, varianza y proporción) a partir de una muestra de la misma.

En estadística hay que diferenciar entre conceptos "parámetros" y "estadísticos".

El término "parámetro" suele utilizarse en referencia a una población, mientras que el término "estadístico" suele utilizarse en referencia a una muestra extraída de dicha población. En la siguiente tabla se muestra la nomenclatura utilizada habitualmente.

+--------------------------------------------+------------------------------------+
| PARÁMETROS (POBLACIONALES)                 | ESTADÍSTICOS (MUESTRALES)          |
+============================================+====================================+
| Media poblacional ($\mu$)                  | Media muestral ($\overline{x}$)    |
+--------------------------------------------+------------------------------------+
| Desviación estándar poblacional ($\sigma$) | Desviación estándar muestral ($s$) |
+--------------------------------------------+------------------------------------+
| Varianza poblacional ($\sigma^{2}$)        | Varianza muestral ($s^{2}$)        |
+--------------------------------------------+------------------------------------+
| Tamaño población ($N$)                     | Tamaño muestra ($n$)               |
+--------------------------------------------+------------------------------------+
| Proporción poblacional ($p$)               | Proporción muestral ($\hat{p}$)    |
+--------------------------------------------+------------------------------------+

Se puede calcular el intervalo en el que se puede asegurar que se encuentra el valor de un parámetro poblacional con un determinado nivel de confianza, obteniendo lo que se conoce como Intervalo de Confianza, con un límite inferior *L~i~* y un límite superior *L~s~*:

$$\text{Intervalo de confianza con nivel de confianza } 1-\alpha = [L_i, L_s]$$

El nivel de confianza ($1-\alpha$) es un valor de 0 a 1 y representa la probabilidad de acertar en la predicción, es decir, la probabilidad de que el valor real del parámetro se encuentre entre los límites del intervalo. Se suele utilizar en % multiplicando por 100. En la expresión del nivel de confianza aparece un valor $\alpha$ (alfa) que se denomina nivel de error o nivel de significación, y representa la probabilidad de no acertar en la predicción.

En la siguiente tabla se indican las fórmulas para calcular los parámetros poblacionales y su posible programación utilizando el lenguaje R.

+-----------------------------------+------------------------------------------------+----------------------------------------------------------------------------------------------------------------------------+---------------------------------------+
| Parámetro a calcular              | Se conoce la varianza poblacional $\sigma^{2}$ | Intervalo de confianza                                                                                                     | Código R                              |
|                                   |                                                |                                                                                                                            |                                       |
|                                   |                                                | (Li, Ls)                                                                                                                   |                                       |
+:=================================:+:==============================================:+:==========================================================================================================================:+:======================================+
| Media poblacional                 | Sí                                             | $$Li = \bar{x}-z_{\frac{\alpha}{2}}\frac{\sigma}{\sqrt{n}}$$                                                               | ``` r                                 |
|                                   |                                                |                                                                                                                            | n=tamaño muestra                      |
| ($\mu$)                           |                                                | $$Ls= \bar{x}+z_{\frac{\alpha}{2}}\frac{\sigma}{\sqrt{n}}$$                                                                | z=qnorm(1-alfa/2,0,1)                 |
|                                   |                                                |                                                                                                                            | m=media muestral                      |
|                                   |                                                |                                                                                                                            | sigma=desviación                      |
|                                   |                                                |                                                                                                                            | poblacional                           |
|                                   |                                                |                                                                                                                            | Li=m-z*(sigma/sqrt(n))                |
|                                   |                                                |                                                                                                                            | Ls=m+z*(sigma/sqrt(n))                |
|                                   |                                                |                                                                                                                            | ```                                   |
+-----------------------------------+------------------------------------------------+----------------------------------------------------------------------------------------------------------------------------+---------------------------------------+
|                                   |                                                | OTRA FORMA                                                                                                                 | ``` r                                 |
|                                   |                                                |                                                                                                                            | Li=qnorm(alfa/2, m,sigma/sqrt(n))     |
|                                   |                                                | El estimador $\bar{X}$ es una variable aleatoria $\text Normal(\bar{x},\frac{\sigma}{\sqrt{n}})$ por lo que:               | Ls=qnorm(1-alfa/2, m,sigma/sqrt(n))   |
|                                   |                                                |                                                                                                                            | ```                                   |
|                                   |                                                | $$Li=\text cuantil\frac{\alpha}{2} de \bar{X}$$                                                                            |                                       |
|                                   |                                                |                                                                                                                            |                                       |
|                                   |                                                | $$Ls=\text cuantil(1-\alpha/2) de \bar{X}$$                                                                                |                                       |
+-----------------------------------+------------------------------------------------+----------------------------------------------------------------------------------------------------------------------------+---------------------------------------+
|                                   | No                                             | $$Li = \bar{x}-z_{\frac{\alpha}{2}}\frac{s}{\sqrt{n}}$$                                                                    | ``` r                                 |
|                                   |                                                |                                                                                                                            | n=tamaño muestra                      |
|                                   | $$n\ge30$$                                     | $$Ls = \bar{x}+z_{\frac{\alpha}{2}}\frac{s}{\sqrt{n}}$$                                                                    | z=qnorm(1-alfa/2,0,1)                 |
|                                   |                                                |                                                                                                                            | m=media muestral                      |
|                                   |                                                |                                                                                                                            | s=desviación muestral                 |
|                                   |                                                |                                                                                                                            | Li=m-z*(s/sqrt(n))                    |
|                                   |                                                |                                                                                                                            | Ls=m+z*(s/sqrt(n))                    |
|                                   |                                                |                                                                                                                            | ```                                   |
+-----------------------------------+------------------------------------------------+----------------------------------------------------------------------------------------------------------------------------+---------------------------------------+
|                                   |                                                | OTRA FORMA                                                                                                                 | ``` r                                 |
|                                   |                                                |                                                                                                                            | Li=qnorm(alfa/2,m,s/sqrt(n))          |
|                                   |                                                | El estimador $\bar{X}$ es una variable aleatoria $\text Normal(\bar{x},\frac{\sigma}{\sqrt{n}})$ por lo que:               | Ls=qnorm(1-alfa/2,m,s/sqrt(n))        |
|                                   |                                                |                                                                                                                            | ```                                   |
|                                   |                                                | $$Li=\text cuantil\frac{\alpha}{2} de \bar{X}$$                                                                            |                                       |
|                                   |                                                |                                                                                                                            |                                       |
|                                   |                                                | $$Ls=\text cuantil(1-\alpha/2) de \bar{X}$$                                                                                |                                       |
+-----------------------------------+------------------------------------------------+----------------------------------------------------------------------------------------------------------------------------+---------------------------------------+
|                                   | No                                             | $$Li = \bar{x}-t_{\frac{\alpha}{2},n-1}\frac{s}{\sqrt{n}}$$                                                                | ``` r                                 |
|                                   |                                                |                                                                                                                            | n=tamaño muestra                      |
|                                   | $$n < 30$$                                     | $$Ls = \bar{x}+t_{\frac{\alpha}{2},n-1}\frac{s}{\sqrt{n}}$$                                                                | t=qt(1-alfa/2,n-1)                    |
|                                   |                                                |                                                                                                                            | m=media muestral                      |
|                                   | Distribución Normal                            |                                                                                                                            | s=desviación muestral                 |
|                                   |                                                |                                                                                                                            | Li=m-t*(s/sqrt(n))                    |
|                                   |                                                |                                                                                                                            | Ls=m+t*(s/sqrt(n))                    |
|                                   |                                                |                                                                                                                            | ```                                   |
+-----------------------------------+------------------------------------------------+----------------------------------------------------------------------------------------------------------------------------+---------------------------------------+
| Varianza poblacional ($\sigma^2$) | No                                             | $$Li = \frac{(n-1)s^{2}}{X^{2}_{\frac{\alpha}{2},n-1}}$$                                                                   | ``` r                                 |
|                                   |                                                |                                                                                                                            | n=tamaño muestra                      |
|                                   |                                                | $$Ls = \frac{(n-1)s^{2}}{X^{2}_{1-\frac{\alpha}{2},n-1}}$$                                                                 | chi.li=qchisq(1-alfa/2,n-1)           |
|                                   |                                                |                                                                                                                            | chi.ls=qchisq(alfa/2,n-1)             |
|                                   |                                                |                                                                                                                            | s=desviación muestral                 |
|                                   |                                                |                                                                                                                            | Li=((n-1)*s^2)/chi.li                 |
|                                   |                                                |                                                                                                                            | Ls=((n-1)*s^2)/chi.ls                 |
|                                   |                                                |                                                                                                                            | ```                                   |
+-----------------------------------+------------------------------------------------+----------------------------------------------------------------------------------------------------------------------------+---------------------------------------+
| Proporción poblacional ($p$)      | \- - -                                         | $$L_{i} = \hat{p}-z_{\alpha/2}\sqrt{\frac{\hat{p}(1-\hat{p})}{n}}$$                                                        | ``` r                                 |
|                                   |                                                |                                                                                                                            | n=tamaño muestra                      |
|                                   |                                                | $$L_{s} = \hat{p}+z_{\alpha/2}\sqrt{\frac{\hat{p}(1-\hat{p})}{n}}$$                                                        | z=qnorm(1-alfa/2,0,1)                 |
|                                   |                                                |                                                                                                                            | p=proporción                          |
|                                   |                                                |                                                                                                                            | Li=p-z*sqrt(p*(1-p)/n)                |
|                                   |                                                |                                                                                                                            | Li=p+z*sqrt(p*(1-p)/n)                |
|                                   |                                                |                                                                                                                            | ```                                   |
+-----------------------------------+------------------------------------------------+----------------------------------------------------------------------------------------------------------------------------+---------------------------------------+
|                                   |                                                | OTRA FORMA                                                                                                                 | ``` r                                 |
|                                   |                                                |                                                                                                                            | Li=qnorm(alfa/2, p,sqrt(p*(1-p)/n))   |
|                                   |                                                | El estimador $\hat{P}$ es una variable aleatoria $\text Normal(\hat{p},\sqrt{{\frac{\hat{p}(1-\hat{p})}{n}}})$ por lo que: | Ls=qnorm(1-alfa/2, p,sqrt(p*(1-p)/n)) |
|                                   |                                                |                                                                                                                            | ```                                   |
|                                   |                                                | $$Li = cuantil\frac{\alpha}{2} de \hat{P}$$                                                                                |                                       |
|                                   |                                                |                                                                                                                            |                                       |
|                                   |                                                | $$Ls = cuantil(1-\alpha/2) de \hat{P}$$                                                                                    |                                       |
+-----------------------------------+------------------------------------------------+----------------------------------------------------------------------------------------------------------------------------+---------------------------------------+

Existen en R funciones predefinidas que se pueden utilizar para los cálculos de algunos intervalos sin tener que programar las fórmulas de la tabla anterior. Son las funciones predefinidas *t.test()* y *prop.test()*, y la función *z.test()* del paquete *BSDA*, que se pueden utilizar como se indica en la siguiente tabla.

+---------------------------------------------+------------------------------------------------------------------------------------------------------------------------------------------+-------------------------------------+
| Parámetro a calcular                        | Código R                                                                                                                                 | Ejemplo                             |
+=============================================+==========================================================================================================================================+=====================================+
| Media poblacional – muestra grande $(\mu)$  | ``` r                                                                                                                                    | ``` r                               |
|                                             | test= z.test(muestra,                                                                                                                    | muestra=rnorm(50,5,1)               |
|                                             |              mu=media muestral,                                                                                                          | prueba=z.test(muestra,              |
|                                             |              sigma.x=desviación típica muestral,                                                                                         |               mu=5,                 |
|                                             |              conf.level = 0.95)                                                                                                          |               sigma.x=1,            |
|                                             | ```                                                                                                                                      |               conf.level=0.95)      |
|                                             |                                                                                                                                          | prueba$conf.int                     |
|                                             | Intervalo:                                                                                                                               | ```                                 |
|                                             |                                                                                                                                          |                                     |
|                                             | ``` r                                                                                                                                    |                                     |
|                                             | test$conf.int                                                                                                                            |                                     |
|                                             | ```                                                                                                                                      |                                     |
+---------------------------------------------+------------------------------------------------------------------------------------------------------------------------------------------+-------------------------------------+
| Media poblacional - muestra pequeña $(\mu)$ | ``` r                                                                                                                                    | ``` r                               |
|                                             | test=t.test(muestra, conf.level = 0.95)                                                                                                  | muestra = c(5,5,4,6,4,5,5,3,3,6)    |
|                                             | ```                                                                                                                                      | prueba=t.test(muestra,              |
|                                             |                                                                                                                                          |               conf.level = 0.95)    |
|                                             | Intervalo:                                                                                                                               | prueba$conf.int                     |
|                                             |                                                                                                                                          | ```                                 |
|                                             | ``` r                                                                                                                                    |                                     |
|                                             | test$conf.int                                                                                                                            |                                     |
|                                             | ```                                                                                                                                      |                                     |
+---------------------------------------------+------------------------------------------------------------------------------------------------------------------------------------------+-------------------------------------+
| Proporción poblacional $p$                  | ``` r                                                                                                                                    | ``` r                               |
|                                             | test=prop.test(ng,                                                                                                                       | prueba=prop.test(70,                |
|                                             |                n,                                                                                                                        |                  100,               |
|                                             |                conf.level = 0.95,                                                                                                        |                  conf.level = 0.95, |
|                                             |                correct=FALSE)                                                                                                            |                  correct=FALSE)     |
|                                             | ```                                                                                                                                      | prueba$conf.int                     |
|                                             |                                                                                                                                          | ```                                 |
|                                             | Intervalo:                                                                                                                               |                                     |
|                                             |                                                                                                                                          |                                     |
|                                             | ``` r                                                                                                                                    |                                     |
|                                             | test$conf.int                                                                                                                            |                                     |
|                                             | ```                                                                                                                                      |                                     |
|                                             |                                                                                                                                          |                                     |
|                                             | NOTA: *n* es el tamaño de la muestra.                                                                                                    |                                     |
|                                             |                                                                                                                                          |                                     |
|                                             | *ng* es el tamaño del grupo de datos de la muestra para el que se calcula la proporción, es decir la proporción muestral p sería *ng/n.* |                                     |
+---------------------------------------------+------------------------------------------------------------------------------------------------------------------------------------------+-------------------------------------+

::: {.callout-tip collapse="true"}
## Copia los ejemplos de la tabla y prúebalos tú mismo aquí

```{webr-r}

```
:::

## 2. Ejemplo: Intervalo de confianza para la media de calificaciones de estudiantes (muestra grande)

***ENUNCIADO***

**Mediante una encuesta, se saben las calificaciones de acceso a la universidad de 74 estudiantes de un curso de la asignatura Estadística del Grado en Ingeniería en Sistemas de Información de la Universidad de Alcalá, de una población de 108 matriculados. Si se supone que las calificaciones tienen una distribución Normal, responder a las siguientes preguntas:**

a)  **Calcular los intervalos de confianza para la media poblacional con niveles de confianza del 90%, 95% y 99%, aplicando las fórmulas.**
b)  **Calcular los intervalos de confianza para la media poblacional con niveles de confianza del 90%, 95% y 99%, utilizando la función *z.test* del paquete *BSDA*.**
c)  **Dibujar una gráfica con los tres intervalos de confianza para compararlos visualmente.**
d)  **Dibujar la función de densidad de probabilidad del estimador con los tres intervalos de confianza.**

***SOLUCIÓN***

Primero hay que leer los datos de las notas, disponibles en el archivo [encuesta.csv](https://hilera.web.uah.es/estadistica/r/datos/encuesta.csv):

```{webr-r}
encuesta = read.csv2("https://raw.githubusercontent.com/nataliamontoyagom/interactiveStatisticsWebsite/main/encuesta.csv")
(nota=encuesta$NOTA)
```

a)  **Calcular los intervalos de confianza para la media poblacional con niveles de confianza del 90%, 95% y 99%.**

No se conoce la varianza poblacional y es una muestra grande (74 \>30), por lo que se aplican las fórmulas:

$$Li = \bar{x}-z_{\frac{\alpha}{2}}\frac{s}{\sqrt{n}}$$

$$Ls = \bar{x}+z_{\frac{\alpha}{2}}\frac{s}{\sqrt{n}}$$ Los comandos en R serían los siguientes:

```{webr-r}
n=length(nota)
m=mean(nota)
s=sd(nota)

#nivel de confianza del 90%
alfa=1-0.9
z=qnorm(1-alfa/2,0,1)
(Li90=m-z*(s/sqrt(n)))
(Ls90=m+z*(s/sqrt(n)))

#nivel de confianza del 95%
alfa=1-0.95
z=qnorm(1-alfa/2,0,1)
(Li95=m-z*(s/sqrt(n)))
(Ls95=m+z*(s/sqrt(n)))

#nivel de confianza del 99%
alfa=1-0.99
z=qnorm(1-alfa/2,0,1)
(Li99=m-z*(s/sqrt(n)))
(Ls99=m+z*(s/sqrt(n)))
```

b)  **Calcular los intervalos de confianza para la media poblacional con niveles de confianza del 90%, 95% y 99%, utilizando la función z.test del paquete BSDA.**

Con *z.test()* se obtienen los mismos valores.

```{webr-r}
install.packages("BSDA")
library(BSDA)

test90=z.test(nota,mu=mean(nota),sigma.x=sd(nota),conf.level=0.90)
test90$conf.int

test95=z.test(nota,mu=mean(nota),sigma.x=sd(nota),conf.level=0.95)
test95$conf.int

test99=z.test(nota,mu=mean(nota),sigma.x=sd(nota),conf.level=0.99)
test99$conf.int
```

Podemos hacer una tabla para comparar los resultados (redondeados con dos decimales), en la que se comprueba que cuanto mayor nivel de confianza menor precisión porque el intervalo es más amplio:

| Nivel de confianza | Intervalo de confianza |
|:------------------:|:----------------------:|
|        90%         |     \[7.81, 8.24\]     |
|        95%         |     \[7.76, 8.28\]     |
|        99%         |     \[7.68, 8.36\]     |

c)  **Dibujar una gráfica con los tres intervalos de confianza para compararlos visualmente.**

Podemos dibujar primero los puntos de la media en cada intervalo, y luego una línea centrada en cada punto desde el límite inferior al límite superior de cada intervalo.

```{webr-r}
plot (c(0.90,0.95,0.99),c(m,m,m), xlim=c(0,2),ylim=c(7,9))
lines(c(0.90,0.90), c(Li90,Ls90))
lines(c(0.95,0.95), c(Li95,Ls95))
lines(c(0.99,0.99), c(Li99,Ls99))
```

d)  **Dibujar la función de densidad de probabilidad del estimador con los tres intervalos de confianza.**

Se dibuja primero la función de densidad de probabilidad del estimador 𝑋̅, que es una variable aleatoria $Normal(\bar{x}, \frac{s}{\sqrt{n}})$.

```{webr-r}
curve(dnorm(x,m,s/sqrt(n),),7,9)
```

Después se añaden segmentos para visualizar los tres intervalos con diferentes colores y tramas, y un leyenda para indicar el nivel de confianza de cada intervalo.

```{webr-r}
curve(dnorm(x,m,s/sqrt(n),),7,9)
segments(0,0,10,0)

segments(Li90,0, Li90,dnorm(Li90,m,s/sqrt(n)))
segments(Ls90,0, Ls90,dnorm(Ls90,m,s/sqrt(n)))

segments(Li95,0, Li95,dnorm(Li95,m,s/sqrt(n)),col=2, lty=2)
segments(Ls95,0, Ls95,dnorm(Ls95,m,s/sqrt(n)),col=2, lty=2)

segments(Li99,0, Li99,dnorm(Li99,m,s/sqrt(n)),col=3, lty=3)
segments(Ls99,0, Ls99,dnorm(Ls99,m,s/sqrt(n)),col=3, lty=3)

legend("topright", 
       inset = 0.05, 
       legend = c("Confianza 90%", "Confianza 95%", "Confianza 99%"), 
       lty= c(1,2,3), 
       col = c(1, 2, 3), 
       cex=1)
```

## 3. Ejemplo: Intervalo de confianza para la media de calificaciones de estudiantes (muestra pequeña)

***ENUNCIADO***

**En el ejemplo anterior, considerar sólo como muestra las calificaciones de los 19 estudiantes del grupo A2 y responder a las siguientes preguntas:**

a)  **Calcular el intervalo de confianza para la media poblacional con nivel de confianza del 95% aplicando las fórmulas.**
b)  **Calcular el intervalo de confianza para la media poblacional con nivel de confianza del 95% utilizando la función *t.test*.**
c)  **Comparar el intervalo obtenido, en el que se ha utilizado un estimador con distribución T-Student por ser muestra pequeña, frente al intervalo que se hubiera obtenido si se hubiese utilizado un estimador con distribución de probabilidad Normal.**
d)  **Representar gráficamente los intervalos de todos los grupos (A1, A2, B1, B2) para un nivel de confianza del 95%, utilizando la función *ggplot()* del paquete *ggplot2*.**
e)  **Representar gráficamente el intervalo de las notas de los alumnos con teléfono con sistema operativo Android y de los alumnos con sistema operativo iOS para un nivel de confianza del 95%, utilizando la función *ggplot()* del paquete *ggplot2*.**

***SOLUCIÓN***

a)  **Calcular el intervalo de confianza para la media poblacional con nivel de confianza del 95% aplicando las fórmulas.**

En este caso, al ser una muestra pequeña (19\<30), se debe suponer que el estimador de la media se adapta mejor a una función de probabilidad T-Student con n-1 (19-1) grados de libertad en lugar de una Normal.

No se conoce la varianza poblacional y es una muestra pequeña, por lo que se aplican las fórmulas:

$$Li = \bar{x}-t_{\frac{\alpha}{2},n-1}\frac{s}{\sqrt{n}}$$

$$Ls = \bar{x}+t_{\frac{\alpha}{2},n-1}\frac{s}{\sqrt{n}}$$

Los comandos en R serían los siguientes:

```{webr-r}
encuesta.A2=encuesta[encuesta$GRUPO=="A2",]
(nota.A2=encuesta.A2$NOTA)
n=length(nota.A2)
m=mean(nota.A2)
s=sd(nota.A2)

#nivel de confianza del 95%
alfa=1-0.95
(t=qt(1-alfa/2,n-1))
(Li=m-t*(s/sqrt(n)))
(Ls=m+t*(s/sqrt(n)))
```

b)  **Calcular el intervalo de confianza para la media poblacional con nivel de confianza del 95% utilizando la función *t.test*.**

Con *t.test()* se obtienen los mismos valores.

```{webr-r}
test=t.test(nota.A2, conf.level = 0.95)
test$conf.int
```

Podemos hacer una tabla para comparar los resultados obtenidos con la muestra pequeña y cola muestra grande:

| Nivel de confianza | Tamaño muestra | Intervalo de confianza |
|:------------------:|:--------------:|:----------------------:|
|        95%         |       74       |     \[7.76, 8.28\]     |
|        95%         |       19       |     \[7.64, 8.89\]     |

c)  **Comparar el intervalo obtenido, en el que se ha utilizado un estimador con distribución T-Student por ser muestra pequeña, frente al intervalo que se hubiera obtenido si se hubiese utilizado un estimador con distribución de probabilidad Normal.**

Si se utilizara un estimador Normal, el intervalo sería:

```{webr-r}
(z=qnorm(1-alfa/2,0,1))
(Li.normal=m-z*(s/sqrt(n)))
(Ls.normal=m+z*(s/sqrt(n)))
```

O bien, usando *z.test*:

```{webr-r}
test=z.test(nota.A2, conf.level = 1-alfa, sigma.x = s)
test$conf.int
```

Podemos hacer una tabla para comparar los resultados:

+--------------------+----------------+----------------------------+
| Nivel de confianza | Tamaño muestra | Intervalo de confianza     |
+:==================:+:==============:+:==========================:+
| 95%                | 19             | Usando estimador T-Student |
|                    |                |                            |
|                    |                | \[7.64, 8.89\]             |
+--------------------+----------------+----------------------------+
| 95%                | 19             | Usando estimador T-Student |
|                    |                |                            |
|                    |                | \[7.68, 8.85\]             |
+--------------------+----------------+----------------------------+

Se puede observar visualmente la diferencia de las funciones de distribución de probabilidad de los dos estimadores (estandarizados, centrados en 0).

```{webr-r}
curve(dt(x,n-1),-5,5)
curve(dnorm(x,0,1),add=TRUE,col="red")
segments(-5,0,5,0)
segments(-t,0, -t,dt(-t,n-1))
segments(t,0, t,dt(t,n-1))
segments(-z,0, -z,dnorm(-z,0,1),col=2,lty=2)
segments(z,0, z,dnorm(z,0,1),col=2, lty=2)
legend("topright", 
       inset = 0.05,
       legend = c("T-Student(n-1)", "Normal(0,1)"),
       lty= c(1,2),
       col = c(1, 2), 
       cex=1)
text(3,0.2, label="t=2.1")
text(3,0.15, label="z=1.96", col=2)
text(0,0.1,"0.95")
```

d)  **Representar gráficamente los intervalos de todos los grupos (A1, A2, B1, B2) para un nivel de confianza del 95%, utilizando la función *ggplot()* del paquete *ggplot2*.**

Se podrían representar gráficamente los intervalos de todos los grupos (A1, A2, B1, B2) al 95% de confianza con el siguiente código[^1]:

[^1]: Código adaptado de <https://rstudio-pubs-static.s3.amazonaws.com/80947_18e337f559fd4ac594506e39901d445a.html>

```{webr-r}
install.packages("ggplot2")
library(ggplot2) #Para utilizar la función ggplot()

install.packages("Rmisc")
library(Rmisc) #Para utilizar la función summarySE()

(resumen.encuesta=summarySE(encuesta, measurevar="NOTA", groupvars="GRUPO"))

g.puntos = ggplot(resumen.encuesta,aes(x=GRUPO,y=NOTA))+geom_point(size=3)+ylim(6,9)

g.puntos

g.intervalos = g.puntos + geom_errorbar(aes(ymin=NOTA-ci, ymax=NOTA+ci), width=0.2) + ggtitle("Intervalo al 95% para la media de las notas según grupo")

g.intervalos
```

e)  **Representar gráficamente el intervalo de las notas de los alumnos con teléfono con sistema operativo Android y de los alumnos con sistema operativo iOS para un nivel de confianza del 95%, utilizando la función *ggplot()* del paquete *ggplot2*.**

```{webr-r}
resumen.encuesta=summarySE(encuesta, measurevar="NOTA", groupvars="SO")

g.puntos = ggplot(resumen.encuesta, aes(x=SO,y=NOTA))+geom_point(size=3)+ylim(6, 9)

g.puntos

g.intervalos = g.puntos+geom_errorbar(aes(ymin=NOTA-ci, ymax=NOTA+ci),width=0.2)+ggtitle("Intervalos al 95% para la media de las nota según SO móvil")

g.intervalos
```

## 4. Ejemplo: Intervalo de confianza para las proporciones de estudiantes que tienen móvil Android

***ENUNCIADO***

**Mediante una encuesta, se sabe que 50 de 74 estudiantes de un curso de la asignatura Estadística del Grado en Ingeniería en Sistemas de Información de la Universidad de Alcalá tienen teléfonos móviles con sistema operativo Android. La población es de 108 estudiantes matriculados. Responder a las siguientes preguntas:**

a)  **Calcular los intervalos de confianza para la proporción poblacional de estudiantes que tienen móvil Android con un nivel de confianza del 90%, 95% y 99% usando las fórmulas.**

b)  **Dibujar la función de densidad de probabilidad del estimador con los tres intervalos de confianza.**

c)  **Inferir el mínimo y máximo número de estudiantes de la población que tienen móvil Android con una confianza del 95%.**

***SOLUCIÓN***

a)  **Calcular los intervalos de confianza para la proporción poblacional de estudiantes que tienen móvil Android con un nivel de confianza del 90%, 95% y 99% usando las fórmulas.**

```{webr-r}
so=encuesta$SO
n=length(so)
so.android=so[so=="Android"]
ng=length(so.android)
(p=ng/n)

# 90%
alfa=1-0.90
z=qnorm(1-alfa/2,0,1)
Li90=p-z*sqrt(p*(1-p)/n)
Ls90=p+z*sqrt(p*(1-p)/n)
c(Li90,Ls90)

# 95%
alfa=1-0.95
z=qnorm(1-alfa/2,0,1)
Li95=p-z*sqrt(p*(1-p)/n)
Ls95=p+z*sqrt(p*(1-p)/n)
c(Li95,Ls95)

# 99%
alfa=1-0.99
z=qnorm(1-alfa/2,0,1)
Li99=p-z*sqrt(p*(1-p)/n)
Ls99=p+z*sqrt(p*(1-p)/n)
```

b)  **Dibujar la función de densidad de probabilidad del estimador con los tres intervalos de confianza.**

Se dibuja primero la función de densidad de probabilidad del estimador $\hat{P}$, que es una variable aleatoria $Normal(\hat{p},\sqrt{\frac{\hat{p}(1-\hat{p})}{n}})$.

```{webr-r}
curve(dnorm(x,p,sqrt(p*(1-p)/n)),0.4,1)
```

Después se añaden segmentos para visualizar los tres intervalos con diferentes colores y tramas, y un leyenda para indicar el nivel de confianza de cada intervalo.

```{webr-r}
curve(dnorm(x,p,sqrt(p*(1-p)/n)),0.4,1)
segments(0.4,0,1,0)
segments(Li90,0, Li90,dnorm(Li90,p,sqrt(p*(1-p)/n)))
segments(Ls90,0, Ls90,dnorm(Ls90,p,sqrt(p*(1-p)/n)))
segments(Li95,0, Li95,dnorm(Li95,p,sqrt(p*(1-p)/n)),col=2, lty=2)
segments(Ls95,0, Ls95,dnorm(Ls95,p,sqrt(p*(1-p)/n)),col=2, lty=2)
segments(Li99,0, Li99,dnorm(Li99,p,sqrt(p*(1-p)/n)),col=3, lty=3)
segments(Ls99,0, Ls99,dnorm(Ls99,p,sqrt(p*(1-p)/n)),col=3, lty=3)
legend("topright", 
       inset = 0.05,
       legend = c("Confianza 90%", "Confianza 95%", "Confianza 99%"),
       lty= c(1,2,3), 
       col = c(1, 2, 3), 
       cex=1)
```

c)  **Inferir el mínimo y máximo número de estudiantes de la población que tienen móvil con Android con una confianza del 95%.**

Como la población es de 108 estudiantes matriculados, sólo hay que multiplicar este valor por los límites del intervalo de confianza. Pero hay que redondear por defecto el valor mínimo (usando la función *floor*) y por exceso el máximo (usando la función *ceiling*).

```{webr-r}
floor(108*Li95)
ceiling(108*Ls95)
```

## 5. Ejercicios propuestos

1.  Mediante una encuesta, se sabe el tiempo en minutos del viaje a la Escuela Politécnica de 74 estudiantes de un curso de la asignatura Estadística del Grado en Ingeniería en Sistemas de Información de la Universidad de Alcalá, de una población de 108 matriculados. Si se supone que tiene una distribución Normal, responder a las siguientes preguntas:
    a.  Calcular los intervalos de confianza para la media poblacional con niveles de confianza del 90%, 95% y 99%, aplicando las fórmulas.

    b.  Dibujar una gráfica con los tres intervalos de confianza para compararlos visualmente.

        ```{webr-r}

        ```
2.  En caso del ejercicio anterior, considerar sólo como muestra los tiempos de viaje de los 19 estudiantes del grupo A2 y responder a las siguientes preguntas:
    a.  Calcular el intervalo de confianza para la media poblacional con nivel de confianza del 95% aplicando las fórmulas.

        ```{webr-r}

        ```
3.  Mediante una encuesta, se sabe que 26 estudiantes de una muestra de 74 de un curso de la asignatura Estadística del Grado en Ingeniería en Sistemas de Información de la Universidad de Alcalá tienen una línea telefónica contratada con las compañías Jazzte/Orange/Simyo. La población es de 108 estudiantes matriculados. Responder a las siguientes preguntas:
    a.  Calcular los intervalos de confianza para la proporción poblacional de estudiantes que tienen una línea telefónica contratada con las compañías Jazzte/Orange/Simyo con un nivel de confianza del 90%, 95% y 99%. NOTA: Utilizar las fórmulas.

    b.  Estimar el mínimo y máximo número de estudiantes de la población que tienen una línea telefónica contratada con las compañías Jazzte/Orange/Simyo móvil con una confianza del 95%.

        ```{webr-r}

        ```
